# Generated by Django 2.1.7 on 2019-04-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveIntegerField(default=0)),
                ('work_done', models.CharField(max_length=1000)),
                ('things_learned', models.CharField(max_length=500)),
            ],
        ),
    ]
