# Generated by Django 2.1.7 on 2019-04-01 18:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 1, 18, 54, 13, 49656, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
