# Generated by Django 2.1.7 on 2019-04-03 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workblog', '0002_daily_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily',
            name='hours',
        ),
    ]
