# Generated by Django 2.2.2 on 2019-09-15 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workblog', '0003_remove_daily_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily',
            old_name='things_learned',
            new_name='tomorrow_work',
        ),
    ]
