# Generated by Django 2.2.2 on 2019-12-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workblog', '0005_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bulit_with_icon',
            field=models.ImageField(default='project_icons/python.png', upload_to='project_icons/'),
            preserve_default=False,
        ),
    ]
