# Generated by Django 2.2.2 on 2019-12-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workblog', '0006_project_bulit_with_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bulit_with_icon',
            field=models.ImageField(blank=True, upload_to='project_icons/'),
        ),
    ]
