# Generated by Django 2.2.2 on 2019-12-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workblog', '0007_auto_20191220_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bulit_with_icon',
            field=models.ImageField(upload_to='project_icons/'),
        ),
    ]
